# Generated by Django 6.0 on 2026-03-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelTable(
            name='payment',
            table='order',
        ),
    ]
