# Generated by Django 6.0 on 2026-03-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_payment_options_alter_payment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'paymnet', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
